# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Triunfo Treinamento e Assessoria
email: meta.brasil@yahoo.com.br
description: > # this means to ignore newlines until "baseurl:"
  Desde 1.999 atendendo em todo o território brasileiro, com
  palestras e cursos na área empresarial, administrativa, jurídica
  e tributária, em parceria com prefeituras, ONGs, associações e sindicatos.
baseurl: "" # the subpath of your site, e.g. /blog
cover: "http://triunfocursos.com.br/img/facebook-banner.png"
#timezone: America/Sao_Paulo
url: "http://triunfocursos.com.br" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

facebook_username: caero.nunes

# Build settings
markdown: kramdown
